---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Check for install at {{ herokuish_ver_install_dir }}
  become: true
  ansible.builtin.stat:
    path: '{{ herokuish_ver_install_dir }}'
  changed_when: false
  register: herokuish_binary
- name: Downloading and installing herokuish
  when: not herokuish_binary.stat.exists
  block:
    - name: Downloading {{ herokuish_tgz_url }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ herokuish_tgz_url }}'
        dest: '{{ herokuish_tmp_tgz }}'
        mode: '644'
        checksum: '{{ herokuish_checksum }}'
    - name: Mkdir {{ herokuish_ver_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ herokuish_ver_install_dir }}'
        mode: '755'
        state: directory
    - name: Unarchive {{ herokuish_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ herokuish_tmp_tgz }}'
        dest: '{{ herokuish_ver_install_dir }}'
        creates: '{{ herokuish_ver_install_dir }}/herokuish'
  always:
    - name: Rm {{ herokuish_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ herokuish_tmp_tgz }}'
        state: absent
- name: Linking {{ herokuish_link }} to {{ herokuish_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ herokuish_exe }}'
    dest: '{{ herokuish_link }}'
    state: link
